# fly.toml app configuration file generated for todo-web-rust on 2023-10-11T15:12:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todo-web-rust"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
